### ISSUE TITLE
The documented Subscription has wrong values for .spec.source and .spec.sourceNamespace

### ISSUE THREAD

**Issue by ludovicmotte** [redhat-gpte-devopsautomation/argocd-namespace-operator#3]
Hi,

The Subscription to create should follow the CatalogSource name & namespace.
See hereunder the fixed values for source & sourceNamespace:

```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: argocd-namespace-operator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: argocd-namespace-operator
  source: argocd-namespace-operator-catalogsource
  sourceNamespace: openshift-operators
```
